<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-OPG4U03" failures="1" tests="3" name="Personal Loan" time="0.112" errors="0" timestamp="2023-09-21T11:40:36 IST">
  <testcase classname="test.TestNGD2" name="ThirdTest" time="0.009"/>
  <testcase classname="test.TestNGD4" name="LoginHomeapi" time="0.004"/>
  <testcase classname="test.TestNGD1" name="Demo" time="0.055">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.TestNGD1.Demo(TestNGD1.java:20)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="test.TestNGD4" name="MobileHomeLogin" time="0.0">
    <ignored/>
  </testcase> <!-- MobileHomeLogin -->
  <testcase classname="test.TestNGD4" name="WebHomelogin" time="0.0">
    <ignored/>
  </testcase> <!-- WebHomelogin -->
  <testcase classname="test.TestNGD1" name="SecondTest" time="0.0">
    <ignored/>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- Personal Loan -->
